sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: c/Z2XomNOPhKJ/FUaKZ5i/L06HpNHACRZ4Xn1woaBfV42El249pw3tPnWprVsabz38aP+wQ+6Dpl+oY9p6LZL1n56w8aGRmHLz2m2+s6rxYhquX6prjecOKqQSjC71RDBXlVuXth7+LNcEIesEFLx7c48GxEPYhmRglXC0O8FINp//S5YeAk8Z1tlP+hpf0TbL8lUWCPzlrzEcwkSV+x9kHufrtIZu6OTyGLsfpqnrUh7FFhHjdO0A7u2Y2d5sO5GabEbkcnb9zn9ruvTbaQVErGDRLFgpxM089kKufBI9uObdbtJOJJhWSTZ5BYW5JedMSV5xLUxr2FdVUHAHTrNS2MUYM5UZ/kYx8V1kI3Kjg+yiBf0rMr6kyaju8sAp/c502AjTVnPxEKvVVpT9erXsla/IJf6vex63+Hl6DKrEG9P7LcbaEAuhA6dExZ0wTOtRF7+lmPUGIWR8O3zubidq6WODfe8RCd+yysumEIIusEqz0aXpQSPd15sNf4gvouVeKwS/lCW5NpDJIWhYZMpI1BGGJ/us9x6SZ9+iy5XRmMboEu/X50j2VjWCP0KNcidUnTw1ddNiUl/05SLG6TDiuxKI3Q+A7FjtW26tg1VTKZGdXZI+8s4C0JK9dhRrvu376Q1JWMhzcukSb0hhGw3r8is1uXd1CB7jS2eYvUGqw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/King-Lear_2266
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy